//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_system_3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBbankEntities : DbContext
    {
        public DBbankEntities()
            : base("name=DBbankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_ACCOUNT> TB_ACCOUNT { get; set; }
        public virtual DbSet<TB_ADMIN> TB_ADMIN { get; set; }
        public virtual DbSet<TB_BANK> TB_BANK { get; set; }
        public virtual DbSet<TB_BRANCH> TB_BRANCH { get; set; }
        public virtual DbSet<TB_CUSTOMER> TB_CUSTOMER { get; set; }
        public virtual DbSet<TB_EMPLOYEE> TB_EMPLOYEE { get; set; }
        public virtual DbSet<TB_LOAN> TB_LOAN { get; set; }
    }
}
