//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_system_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BRANCH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_BRANCH()
        {
            this.TB_CUSTOMER = new HashSet<TB_CUSTOMER>();
            this.TB_EMPLOYEE = new HashSet<TB_EMPLOYEE>();
            this.TB_LOAN = new HashSet<TB_LOAN>();
        }
    
        public int BRANCH_NUMBER { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> CODE { get; set; }
    
        public virtual TB_BANK TB_BANK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CUSTOMER> TB_CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_EMPLOYEE> TB_EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_LOAN> TB_LOAN { get; set; }
    }
}
