//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_system_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_EMPLOYEE()
        {
            this.TB_CUSTOMER = new HashSet<TB_CUSTOMER>();
        }
    
        public int SSN_EMPLOYEE { get; set; }
        public int BRANCH_NUMBER { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string POSTION_ { get; set; }
        public Nullable<decimal> PHONE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CUSTOMER> TB_CUSTOMER { get; set; }
    }
}
