//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_system_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LOAN
    {
        public int LOAN_NUMBER { get; set; }
        public Nullable<int> SSN_EMPLOYEE { get; set; }
        public Nullable<int> BRANCH_NUMBER { get; set; }
        public Nullable<int> ACCOUNT_NUMBER { get; set; }
        public Nullable<int> LOAN_AMOUNT { get; set; }
        public string LOAN_TYPE { get; set; }
        public string LOAN_STATUS { get; set; }
    }
}
